### ISSUE TITLE
Installing 1password CLI v. 1.10.3 

### ISSUE THREAD

**Issue by luisgc93** [wandera/1password-client#38]
Unfortunately version 1.10.3 of OP CLI is not available through `brew`. I uninstalled the latest version and then ran `pip install 1pasword`. I assumed from the readme that the python package would somehow install the right version of 1password-cli:

`````
The above commands will check op is present already and if not will install the best op cli it can work out plus 
the python client itself. This is currently fixed at op version 1.10.3 to ensure compatibility.
`````
However when I try to instantiate the client and I input all my credentials I get the following error:
`````
*** pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: op.
`````

Any help is appreciated. Thanks in advance!

*UPDATE - When I try to instantiate the client with the latest OP CLI version, I get the following error instead (which I guess is expected since the version is not supported):
`````
*** OSError: [Errno 5] Input/output error
`````

**Comment by dtpryce** [comment]
Just to clarify you have used the OnePassword cask as outlined here: https://developer.1password.com/docs/cli/get-started/#install

We haven't looked at recent versions in a while but could see if we support the latest, would that help you here?

**Comment by dtpryce** [comment]
Ahh I understand what has happened now ... here we are supporting 1Password 7 or earlier, however they have recently upgraded to 1Password8 and hence the cli has had an overhaul. I will work out how to maintain the old cli and hopefully in the future we will update to handle the newer cli / client.

**Comment by dtpryce** [comment]
ok @luisgc93 I have updated the README to be clearer. If you wish to install the version yourself you can but please use the CLI1 list you can find here https://app-updates.agilebits.com/product_history/CLI I have also quickly tested the highest version for that CLI with our client and appears to work fine (1.12.5) and updated the client to install that so you can also use `pip install 1password` to handle the `op` installation. I will also make an issue to investigate CLI2 and it's integration here. 

I am closing this issue since I think it's resolved. Please re-open with any further issues.
